### ISSUE TITLE
Redis Error

### ISSUE THREAD

**Issue by Snuffy4** [retroroyale/ClashRoyale#1]
What should I do if I get an error when starting the server?
`[Error] StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). UnableToConnect on 127.0.0.1:6379/Interactive, Initializing, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 1s ago, last-write: 1s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 18s ago, v: 2.0.571.20511
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(Object configuration, TextWriter log) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 934
   at ClashRoyale.Database.Redis..ctor() in C:\Users\kisel\Desktop\ClashRoyale-master\ClashRoyale\ClashRoyale\Database\Redis.cs:line 45`

**Comment by Incr3dible** [comment]
Do you have a Redis server running?

**Comment by Snuffy4** [comment]
Yeah, but maybe I have an old one. What is suitable for Windows?

**Comment by Incr3dible** [comment]
Have you changed the host and the password in the settings? (config.json)

**Comment by Snuffy4** [comment]
Yes, could you give a link to Redis for me to reinstall it?

**Comment by Incr3dible** [comment]
Here are some windows versions:
https://github.com/dmajkic/redis/downloads

**Comment by Incr3dible** [comment]
This one should work:
https://github.com/ServiceStack/redis-windows/raw/master/downloads/redis-latest.zip

(I'm on mobile and can't check that right now)

**Comment by Snuffy4** [comment]
Thank you, do you have a patched client?

**Comment by Incr3dible** [comment]
Yes I have, but as I said i'm on mobile rn.
As soon as I have time to work on it again I gonna add a patched client.

**Comment by Snuffy4** [comment]
Good, and for health you need to change client_global.csv?

**Comment by Incr3dible** [comment]
Yes you have to change "PEPPER_ENABLED" to false or just leave it empty because the server is using RC4 as crypto.
