### ISSUE TITLE
Why use Netty?

### ISSUE THREAD

**Issue by moien007** [retroroyale/ClashRoyale#11]
Hi,

Why use Netty? .NET Core sockets are enough powerful. 
Doubt? See:
- [What’s new for performance in .NET Core 2.0 - Ben Adams](https://cdn.ageofascent.net/assets/2017/Corestart-Whats-new-performance-dotnet-core-2-0.pdf): **SocketAsyncEventArgs + 360% faster**
- [ASP.NET Core 2.1 release notes](https://devblogs.microsoft.com/aspnet/asp-net-core-2-1-0-now-available/): **Managed sockets replace libuv as Kestrel's default transport.**

Regards.

**Comment by Incr3dible** [comment]
If they are faster in general then also with Netty

**Comment by moien007** [comment]
> If they are faster in general then also with Netty

What about lightweight-ness?

**Comment by Incr3dible** [comment]
nameless said add text... well... here it is

**Comment by zzVertigo** [comment]
Netty is a nice framework one way or another imo plus re-implementing the entire network would just be a huge hassle. If you really want it that bad just fork it and make a new branch.

Enough said Xd
