### ISSUE TITLE
[Feature Req] More settings in config.json, SQLite support.

### ISSUE THREAD

**Issue by MasterDevX** [retroroyale/ClashRoyale#18]
1. It would be great if some another values, such as starting trophies, gems and gold can be set in config.json file.
2. One more thing that might be useful is to add SQLite DataBase support, so setting up MySQL or Redis will be unnecessary and all data will be stored in a single local DB file.

**Comment by Incr3dible** [comment]
1. You can simply set the starting value of resources & trophies in the code 
2. You can easily setup both, MySql and Redis, SQLite would be much slower at a lot of players

**Comment by MasterDevX** [comment]
> * You can simply set the starting value of resources & trophies in the code
> * You can easily setup both, MySql and Redis, SQLite would be much slower at a lot of players

Thx for reply
