### ISSUE TITLE
Edit IP Client

### ISSUE THREAD

**Issue by Snuffy4** [retroroyale/ClashRoyale#2]
How to change IP game.clashroyaleapp.com your own? When changing libg.so writes that the game is installed incorrectly
(I can't find you in Discord.)

**Comment by Incr3dible** [comment]
The hostname has to be 23 characters long. Did you try to add spaces after the ip?
You can also change the host with hosts editor.

**Comment by Snuffy4** [comment]
Thanks, fixed. Why can't I create a clan?

**Comment by Incr3dible** [comment]
You can also join our server:
https://discord.gg/t5raXDh

(please wait a few minutes, you will receive a role to chat)
