### ISSUE TITLE
Apk and tutorial to edit it 

### ISSUE THREAD

**Issue by Killuacrow** [retroroyale/ClashRoyale#27]
Hi, long ago I found this beautiful project in a forum with the relative apk and the tutorial to modify it, could you give me that link and maybe add it in the description on github? thank you so much

**Comment by Incr3dible** [comment]
Hey Killuacrow,
in the [Wiki](https://github.com/retroroyale/ClashRoyale/wiki) you can find the tutorial for the patches required for battles. 
I haven't added any other tutorials so you might find some on YouTube for the hosts.

**Comment by Killuacrow** [comment]
can you please tell me the apk version for this server? and if i can edit the original apk with the server version?

**Comment by Incr3dible** [comment]
The version is 1.9.2 as it's in the readme.

**Comment by Killuacrow** [comment]
forgive me, I exchanged it for the server version

**Comment by Incr3dible** [comment]
You can't use a newer client for this server without editing it.

**Comment by Killuacrow** [comment]
http://forum.ragezone.com/f857/release-clash-royale-server-1161252/
