### ISSUE TITLE
How unlock all deck and max level?

### ISSUE THREAD

**Issue by keirozCode** [retroroyale/ClashRoyale#28]
Please answer
Thanks

**Comment by Incr3dible** [comment]
Open chests and upgrade them.

**Comment by Mahi-Uddin** [comment]
> Please answer
> Thanks

https://github.com/retroroyale/ClashRoyale/blob/master/src/ClashRoyale/Logic/Home/Decks/Deck.cs#L37
The deck is encoded here, do the rest on your own xD
