### ISSUE TITLE
This isn't an issue

### ISSUE THREAD

**Issue by OverallGod** [retroroyale/ClashRoyale#29]
Sorry for creating an issue when this isnt an issue I know that's not what githubs for but I just wanted to say thank you for all the work your putting into this project. Almost everyday I see that you've added or fixed something. I know there are others servers but none of them are "new" anyways the entire point of this was to say thanks and tell you your doing great because you never know what someone is going through and its always good to spread joy. I hope you have a great day and spread this kindness to others. You can close this whenever you see it.
I am a novice/intermediate c++ programmer

**Comment by Incr3dible** [comment]
I appreciate that, thank you!
