### ISSUE TITLE
"bug"?

### ISSUE THREAD

**Issue by TrrIx** [retroroyale/ClashRoyale#30]
i know that u r german xD
Ich weis nicht ob man das als Bug bezeichnen kann, aber es ist irgendwie sinnlos, dass man in Arena 1 Karten aus Arena 9 bekommt. xD

**Comment by Incr3dible** [comment]
An das habe ich auch schon gedacht und werde es evtl. mal ändern.

**Comment by Incr3dible** [comment]
Man müsse aber erst noch das Matchmaking verbessern, sonst haben Arena 1 Spieler keine Chance, auch wenn man immer gewinnt (bis jetzt) macht es nicht viel Spaß.

**Comment by TrrIx** [comment]
Okay, sonst gefällt mir der Server sehr. :)

**Comment by Incr3dible** [comment]
Danke, freut mich ^^
Sollten demnächst mehr Updates kommen
