### ISSUE TITLE
How to enable lesions on the server? I want to do it.

### ISSUE THREAD

**Issue by TheDcLikes** [retroroyale/ClashRoyale#36]
How to enable lesions on the server? I want to do it. Help compile the server with les included. I will be grateful.

**Comment by Incr3dible** [comment]
There is no simple way, on enabling the tutorials. That has to be implemented first.

**Comment by TheDcLikes** [comment]
@Incr3dible that is, you can’t turn on the lesion system in any way?  Will players always win?
