### ISSUE TITLE
How to unlock all card and max level?

### ISSUE THREAD

**Issue by HyperCrack** [retroroyale/ClashRoyale#7]
How to unlock all card and all max level (if create new account)? And why can't use slot card 2345

Thanks you.

**Comment by Incr3dible** [comment]
You can uncommit this https://github.com/retroroyale/ClashRoyale/blob/master/ClashRoyale/ClashRoyale/Logic/Home/Decks/Deck.cs#L19
to get all cards.

Slot's aren't done yet.
